# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: MMITVBundle\Form\Type\RegistrationFormType
        tags:
            - { name: "form.type", alias: "app_user_registration" }

    app.form.invitation:
        class: MMITVBundle\Form\Type\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
            - { name: "form.type", alias: "app_invitation_type" }

    app.form.data_transformer.invitation:
        class: MMITVBundle\Form\Type\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false
