<?php

namespace MMITVBundle\Entity;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends \Doctrine\ORM\EntityRepository
{
}
